version: '3.9'

services:
    api:
        build:
            context: .
        ports:
            - 3000:3000
        environment:
            DB_URL: postgres://postgres:postgres@db:5432/nodejs-weatherapp-db
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:17
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: nodejs-weatherapp-db
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5
