openapi: 3.0.3
info:
    title: Weather App API
    description: Weather management API (CRUD operations)
    version: 1.0.0
    contact:
        email: simonlibiger@gmail.com

servers:
    - url: http://localhost:3000
      description: Local Server

tags:
    - name: weathers
      description: Everything about Weathers

paths:
    /weathers:
        get:
            $ref: './resources/weathers.yaml#/get'
        post:
            $ref: './resources/weathers.yaml#/post'
    /weathers/list:
        get:
            $ref: './resources/weathers.yaml#/getList'
    /weathers/{id}:
        get:
            $ref: './resources/weathers.yaml#/getById'
        put:
            $ref: './resources/weathers.yaml#/putById'
        patch:
            $ref: './resources/weathers.yaml#/patchById'
        delete:
            $ref: './resources/weathers.yaml#/deleteById'
